name: Main workflow
on:
  ## This tries to avoid unessesary pushes to forked repo
  ## development branches. No sense in a dev building every
  ## time they push for a PR and no one should be working on
  ## common branches in their fork.
  #push:
    #branches:
      #- master
      #- develop
      #- 'hotfix/**'
      #- 'release/**'
      #- 'feature/**'
  ## Any pull request. Yes the syntax looks weird
  pull_request:

jobs:
  informer:
    name: Get some info
    runs-on: ubuntu-latest
    env:
      ML: |
        I can has "quotes"?
      REGULAR: UNLEADED
      UNLEADED: "Premium"

    steps:
      - name: info
        run:  |
          echo "        GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo "      GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}"
          echo "             GITHUB_SHA: ${GITHUB_SHA}"
          echo " "
          echo "                ES Port: ${{ job.services.elasticsearch.ports[9200] }}"


          echo -e "Multi-line ${ML}"
          echo -e " REGULAR: ${REGULAR}"
          echo -e "UNLEADED: ${UNLEADED}"



  test:
    name: Test the loader on ${{matrix.operating-system}}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        #operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        operating-system: [ubuntu-latest]

    steps:
      - name: Get the code
        uses: actions/checkout@v2

      - name: Set up node
        uses:  actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run:  |
          npm ci

      - name: Run tests
        run:  |
          npm test
        env:
          CI: true

      - name: Archive test artifacts
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: coverage

  integration_tests:
    name: Run Integration Tests (Linux)
    runs-on: ubuntu-latest
    needs: test


    services:
      elasticsearch:
        image: elasticsearch:7.17.5
        env:
            discovery.type: single-node
            ES_JAVA_OPTS: -Xms750m -Xmx750m
        ports:
          ## NOTE: This will be exposed as a random port referenced below by job.services.elasticsearch.ports[9200]
          - 9200/tcp
        options: --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:

      - name: Override default configuration
        run: |
          CONFIG_OVERRIDE="
            {
              \"pipeline\": {
                  \"source\": {
                      \"module\": \"./lib/sources/github-resource-source\",
                      \"config\": {
                          \"repoUrl\": \"https://github.com/nciocpl/r4r-loader\",
                          \"branchName\": \"ticket/8-es-update\",
                          \"resourcesPath\": \"/integration-tests/data/resources\",
                          \"authentication\": {
                              \"token\": \"${GITHUB_TOKEN}\"
                          }
                      }
                  },
                  \"transformers\": [
                      {
                          \"module\": \"./lib/transformers/netlifymd-resource-transformer\",
                          \"config\": {
                            \"mappingUrls\": {
                                \"docs\": \"https://raw.githubusercontent.com/nciocpl/r4r-loader/ticket/8-es-update/integration-tests/data/data/docs.json\",
                                \"researchAreas\": \"https://raw.githubusercontent.com/nciocpl/r4r-loader/ticket/8-es-update/integration-tests/data/data/researchAreas.json\",
                                \"researchTypes\": \"https://raw.githubusercontent.com/nciocpl/r4r-loader/ticket/8-es-update/integration-tests/data/data/researchTypes.json\",
                                \"toolTypes\": \"https://raw.githubusercontent.com/nciocpl/r4r-loader/ticket/8-es-update/integration-tests/data/data/toolTypes.json\"
                            }
                          }
                      }
                  ],
                  \"loader\": {
                      \"module\": \"./lib/loaders/elastic-resource-loader\",
                      \"config\": {
                        \"eshosts\": [ \"http://localhost:${{ job.services.elasticsearch.ports[9200] }}\" ],
                        \"daysToKeep\": 10,
                        \"aliasName\": \"r4r_v1\",
                        \"mappingPath\": \"es-mappings/mappings.json\",
                        \"settingsPath\": \"es-mappings/settings.json\"
                      }
                  }
              }
            }
          "
          echo "NODE_CONFIG=\"${CONFIG_OVERRIDE}\"" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Get the code
        uses: actions/checkout@v2

      - name: Set up node
        uses:  actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run:  |
          npm ci

      - name: Run the loader to put data in Elasticsearch.
        run:  |
          echo "-----------"
          echo "CN: ${NODE_CONFIG}"
          echo "-----------"
          node index.js

      - name: Run Integration Test
        ## Normally bash runs with -e which exits the shell upon hitting
        ## an error which breaks our capturing of those errors.
        shell: bash --noprofile --norc -o pipefail {0}
        run: |
              ## Run Karate
              cd integration-tests && ./bin/karate ./features
              ## Store the exit code off so we can pass this step and
              ## capture the test output in the next step, but still
              ## fail the entire job
              echo "TEST_EXIT_CODE=$?" >> $GITHUB_ENV
              exit 0

      - name: Upload Integration test results
        uses: actions/upload-artifact@v1
        with:
          name: integration-test-results
          path: integration-tests/target

      - name: Fail build on bad tests
        run: |
              ## Check if we had errors on the test step, and if so, fail the job
              if [ $TEST_EXIT_CODE -ne 0 ]; then
                echo "Tests Failed -- See Run Integration Test step or integration-test-results artifact for more information"
                exit $TEST_EXIT_CODE
              else
                echo "Tests passed"
              fi